### ISSUE TITLE
Can't do unit testing after installing

### ISSUE THREAD

**Issue by PabloReyes** [Codeception/YiiBridge#1]
I just updated Codeception to 1.8 and installed YiiBridge. I also removed the module "Unit" from my unit.suite.yml. Now it looks like this:

```
class_name: CodeGuy
modules:
    enabled: [Yii1, CodeHelper]
    config:
        Yii1:
            appPath: '../index-test.php'
            url: 'http://my.website.dev'
```

I'm not doing functional testing, but I added 

``` php
require_once __DIR__.'/../_data/YiiBridge/yiit.php';
```

to /functional/_bootstrap.php just as the installation process suggest. 

I run 

```
php codecept.phar build
```

and ran my unit test:

```
$php codecept.phar run tests/unit/DBConstraintsTest.php
  [Codeception\Exception\ModuleConfig]                                                                                     
  Yii1 module is not configured!                                                                                           

  Codeception-Yii Bridge is not launched. In order to run tests you need to install https://github.com/Codeception/YiiBri  
  dgeImplement function 'launch_codeception_yii_bridge' to load all Codeception overrides  
```

After that, I added yiit.php to /unit/_bootstrap.php as well, but I keep getting the same error. 

YiiBridge is supposed to be a bridge for Functional Testing in Yii, so why is it bothering me when trying to unit test?

Thanks!
